# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799b75fad190e954d35fd1f20b3eca4fd95546ce6f2d56e9b220832cb57a020a8649a05af668a524613d5e974df9ffb123e496e81fd172e736428da8f497e9fb

test:
  secret_key_base: 93e902898c2c98a15171d28620831f5774f8f85dad3880d54c203e5b8af172ae92ee8c1df99aadd98f531c0aa1de008928bac790958931259899ff236d1e1f88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
